## Source: Modified from https://gist.github.com/pamelafox/986163

country_groups = [
{'continent': 'Europe', 'country': 'Andorra'},
{'continent': 'Asia', 'country': 'Afghanistan'},
{'continent': 'North America', 'country': 'Antigua and Barbuda'},
{'continent': 'Europe', 'country': 'Albania'},
{'continent': 'Asia', 'country': 'Armenia'},
{'continent': 'Africa', 'country': 'Angola'},
{'continent': 'South America', 'country': 'Argentina'},
{'continent': 'Europe', 'country': 'Austria'},
{'continent': 'Oceania', 'country': 'Australia'},
{'continent': 'Asia', 'country': 'Azerbaijan'},
{'continent': 'North America', 'country': 'Barbados'},
{'continent': 'Asia', 'country': 'Bangladesh'},
{'continent': 'Europe', 'country': 'Belgium'},
{'continent': 'Africa', 'country': 'Burkina Faso'},
{'continent': 'Europe', 'country': 'Bulgaria'},
{'continent': 'Asia', 'country': 'Bahrain'},
{'continent': 'Africa', 'country': 'Burundi'},
{'continent': 'Africa', 'country': 'Benin'},
{'continent': 'Asia', 'country': 'Brunei Darussalam'},
{'continent': 'South America', 'country': 'Bolivia'},
{'continent': 'South America (Portuguese)', 'country': 'Brazil'},
{'continent': 'North America', 'country': 'Bahamas'},
{'continent': 'Asia', 'country': 'Bhutan'},
{'continent': 'Africa', 'country': 'Botswana'},
{'continent': 'Europe', 'country': 'Belarus'},
{'continent': 'North America', 'country': 'Belize'},
{'continent': 'North America', 'country': 'Canada'},
{'continent': 'Africa', 'country': 'Democratic Republic of the Congo'},
{'continent': 'Africa', 'country': 'Republic of the Congo'},
{'continent': 'Africa', 'country': "C\xc3\xb4te d'Ivoire"},
{'continent': 'South America', 'country': 'Chile'},
{'continent': 'Africa', 'country': 'Cameroon'},
{'continent': 'Asia', 'country': "People's Republic of China"},
{'continent': 'South America', 'country': 'Colombia'},
{'continent': 'North America', 'country': 'Costa Rica'},
{'continent': 'North America', 'country': 'Cuba'},
{'continent': 'Africa', 'country': 'Cape Verde'},
{'continent': 'Asia', 'country': 'Cyprus'},
{'continent': 'Europe', 'country': 'Czech Republic'},
{'continent': 'Europe', 'country': 'Germany'},
{'continent': 'Africa', 'country': 'Djibouti'},
{'continent': 'Europe', 'country': 'Denmark'},
{'continent': 'North America', 'country': 'Dominica'},
{'continent': 'North America', 'country': 'Dominican Republic'},
{'continent': 'South America', 'country': 'Ecuador'},
{'continent': 'Europe', 'country': 'Estonia'},
{'continent': 'Africa', 'country': 'Egypt'},
{'continent': 'Africa', 'country': 'Eritrea'},
{'continent': 'Africa', 'country': 'Ethiopia'},
{'continent': 'Europe', 'country': 'Finland'},
{'continent': 'Oceania', 'country': 'Fiji'},
{'continent': 'Europe', 'country': 'France'},
{'continent': 'Africa', 'country': 'Gabon'},
{'continent': 'Asia', 'country': 'Georgia'},
{'continent': 'Africa', 'country': 'Ghana'},
{'continent': 'Africa', 'country': 'The Gambia'},
{'continent': 'Africa', 'country': 'Guinea'},
{'continent': 'Europe', 'country': 'Greece'},
{'continent': 'North America', 'country': 'Guatemala'},
{'continent': 'North America', 'country': 'Haiti'},
{'continent': 'Africa', 'country': 'Guinea-Bissau'},
{'continent': 'South America', 'country': 'Guyana'},
{'continent': 'North America', 'country': 'Honduras'},
{'continent': 'Europe', 'country': 'Hungary'},
{'continent': 'Asia', 'country': 'Indonesia'},
{'continent': 'Europe', 'country': 'Republic of Ireland'},
{'continent': 'Asia', 'country': 'Israel'},
{'continent': 'Asia', 'country': 'India'},
{'continent': 'Asia', 'country': 'Iraq'},
{'continent': 'Asia', 'country': 'Iran'},
{'continent': 'Europe', 'country': 'Iceland'},
{'continent': 'Europe', 'country': 'Italy'},
{'continent': 'North America', 'country': 'Jamaica'},
{'continent': 'Asia', 'country': 'Jordan'},
{'continent': 'Asia', 'country': 'Japan'},
{'continent': 'Africa', 'country': 'Kenya'},
{'continent': 'Asia', 'country': 'Kyrgyzstan'},
{'continent': 'Oceania', 'country': 'Kiribati'},
{'continent': 'Asia', 'country': 'North Korea'},
{'continent': 'Asia', 'country': 'South Korea'},
{'continent': 'Asia', 'country': 'Kuwait'},
{'continent': 'Asia', 'country': 'Lebanon'},
{'continent': 'Europe', 'country': 'Liechtenstein'},
{'continent': 'Africa', 'country': 'Liberia'},
{'continent': 'Africa', 'country': 'Lesotho'},
{'continent': 'Europe', 'country': 'Lithuania'},
{'continent': 'Europe', 'country': 'Luxembourg'},
{'continent': 'Europe', 'country': 'Latvia'},
{'continent': 'Africa', 'country': 'Libya'},
{'continent': 'Africa', 'country': 'Madagascar'},
{'continent': 'Oceania', 'country': 'Marshall Islands'},
{'continent': 'Europe', 'country': 'Macedonia'},
{'continent': 'Africa', 'country': 'Mali'},
{'continent': 'Asia', 'country': 'Myanmar'},
{'continent': 'Asia', 'country': 'Mongolia'},
{'continent': 'Africa', 'country': 'Mauritania'},
{'continent': 'Europe', 'country': 'Malta'},
{'continent': 'Africa', 'country': 'Mauritius'},
{'continent': 'Asia', 'country': 'Maldives'},
{'continent': 'Africa', 'country': 'Malawi'},
{'continent': 'North America', 'country': 'Mexico'},
{'continent': 'Asia', 'country': 'Malaysia'},
{'continent': 'Africa', 'country': 'Mozambique'},
{'continent': 'Africa', 'country': 'Namibia'},
{'continent': 'Africa', 'country': 'Niger'},
{'continent': 'Africa', 'country': 'Nigeria'},
{'continent': 'North America', 'country': 'Nicaragua'},
{'continent': 'Europe', 'country': 'Kingdom of the Netherlands'},
{'continent': 'Europe', 'country': 'Norway'},
{'continent': 'Asia', 'country': 'Nepal'},
{'continent': 'Oceania', 'country': 'Nauru'},
{'continent': 'Oceania', 'country': 'New Zealand'},
{'continent': 'Asia', 'country': 'Oman'},
{'continent': 'North America', 'country': 'Panama'},
{'continent': 'South America', 'country': 'Peru'},
{'continent': 'Oceania', 'country': 'Papua New Guinea'},
{'continent': 'Asia', 'country': 'Philippines'},
{'continent': 'Asia', 'country': 'Pakistan'},
{'continent': 'Europe', 'country': 'Poland'},
{'continent': 'Europe', 'country': 'Portugal'},
{'continent': 'Oceania', 'country': 'Palau'},
{'continent': 'South America', 'country': 'Paraguay'},
{'continent': 'Asia', 'country': 'Qatar'},
{'continent': 'Europe', 'country': 'Romania'},
{'continent': 'Europe', 'country': 'Russia'},
{'continent': 'Africa', 'country': 'Rwanda'},
{'continent': 'Asia', 'country': 'Saudi Arabia'},
{'continent': 'Oceania', 'country': 'Solomon Islands'},
{'continent': 'Africa', 'country': 'Seychelles'},
{'continent': 'Africa', 'country': 'Sudan'},
{'continent': 'Europe', 'country': 'Sweden'},
{'continent': 'Asia', 'country': 'Singapore'},
{'continent': 'Europe', 'country': 'Slovenia'},
{'continent': 'Europe', 'country': 'Slovakia'},
{'continent': 'Africa', 'country': 'Sierra Leone'},
{'continent': 'Europe', 'country': 'San Marino'},
{'continent': 'Africa', 'country': 'Senegal'},
{'continent': 'Africa', 'country': 'Somalia'},
{'continent': 'South America', 'country': 'Suriname'},
{'continent': 'Africa', 'country': 'S\xc3\xa3o Tom\xc3\xa9 and Pr\xc3\xadncipe'},
{'continent': 'Asia', 'country': 'Syria'},
{'continent': 'Africa', 'country': 'Togo'},
{'continent': 'Asia', 'country': 'Thailand'},
{'continent': 'Asia', 'country': 'Tajikistan'},
{'continent': 'Asia', 'country': 'Turkmenistan'},
{'continent': 'Africa', 'country': 'Tunisia'},
{'continent': 'Oceania', 'country': 'Tonga'},
{'continent': 'Asia', 'country': 'Turkey'},
{'continent': 'North America', 'country': 'Trinidad and Tobago'},
{'continent': 'Oceania', 'country': 'Tuvalu'},
{'continent': 'Africa', 'country': 'Tanzania'},
{'continent': 'Europe', 'country': 'Ukraine'},
{'continent': 'Africa', 'country': 'Uganda',},
{'continent': 'North America', 'country': 'United States'},
{'continent': 'South America', 'country': 'Uruguay'},
{'continent': 'Asia', 'country': 'Uzbekistan'},
{'continent': 'Europe', 'country': 'Vatican City'},
{'continent': 'South America', 'country': 'Venezuela'},
{'continent': 'Asia', 'country': 'Vietnam'},
{'continent': 'Oceania', 'country': 'Vanuatu'},
{'continent': 'Asia', 'country': 'Yemen'},
{'continent': 'Africa', 'country': 'Zambia'},
{'continent': 'Africa', 'country': 'Zimbabwe'},
{'continent': 'Africa', 'country': 'Algeria'},
{'continent': 'Europe', 'country': 'Bosnia and Herzegovina'},
{'continent': 'Asia', 'country': 'Cambodia'},
{'continent': 'Africa', 'country': 'Central African Republic'},
{'continent': 'Africa', 'country': 'Chad'},
{'continent': 'Africa', 'country': 'Comoros'},
{'continent': 'Europe', 'country': 'Croatia'},
{'continent': 'Asia', 'country': 'East Timor'},
{'continent': 'North America', 'country': 'El Salvador'},
{'continent': 'Africa', 'country': 'Equatorial Guinea'},
{'continent': 'North America', 'country': 'Grenada'},
{'continent': 'Asia', 'country': 'Kazakhstan'},
{'continent': 'Asia', 'country': 'Laos'},
{'continent': 'Oceania', 'country': 'Federated States of Micronesia'},
{'continent': 'Europe', 'country': 'Moldova'},
{'continent': 'Europe', 'country': 'Monaco'},
{'continent': 'Europe', 'country': 'Montenegro'},
{'continent': 'Africa', 'country': 'Morocco'},
{'continent': 'North America', 'country': 'Saint Kitts and Nevis'},
{'continent': 'North America', 'country': 'Saint Lucia'},
{'continent': 'North America', 'country': 'Saint Vincent and the Grenadines'},
{'continent': 'Oceania', 'country': 'Samoa'},
{'continent': 'Europe', 'country': 'Serbia'},
{'continent': 'Africa', 'country': 'South Africa'},
{'continent': 'Europe', 'country': 'Spain'},
{'continent': 'Asia', 'country': 'Sri Lanka'},
{'continent': 'Africa', 'country': 'Swaziland'},
{'continent': 'Europe', 'country': 'Switzerland'},
{'continent': 'Asia', 'country': 'United Arab Emirates'},
{'continent': 'Europe', 'country': 'United Kingdom'}
]
